---

- hosts: all
  tasks:
    - name: install packages
      yum:
        name:
          - perl-JSON-XS 
          - perl-Regexp-Assemble
          - perl-Template-Toolkit
          - perl-MIME-EncWords
          - td-agent

    - name: td-agent setup
      lineinfile:
        dest:   /etc/td-agent/td-agent.conf
        insertafter: EOF
        regexp: "@include {{TOOLHOME}}"
        line:   "@include {{TOOLHOME}}/conf/fluentd/fluentd_foucault03.conf"

    - name: "foucault03 crontab setup"
      cron:
        user: td-agent
        name: "foucault03 cleanup batch"
        minute: "02"
        job: "{{TOOLHOME}}/bin/foucaultcron cleanup"

    - name: "foucault03 crontab setup"
      cron:
        user: td-agent
        name: "foucault03 prepare batch"
        minute: "00-55/5"
        job: "{{TOOLHOME}}/bin/foucaultcron prepare"

    - name: "foucault03 crontab setup"
      cron:
        user: td-agent
        name: "foucault03 deliver_flash batch"
        minute: "01-56/5"
        job: "{{TOOLHOME}}/bin/foucaultcron deliver_flash"

    - name: "foucault03 crontab setup"
      cron:
        user: td-agent
        name: "foucault03 deliver_daily batch"
        hour: "09"
        minute: "05"
        job: "{{TOOLHOME}}/bin/foucaultcron deliver_daily"

    - name: install gems fluent-plugin-concat
      gem:
        executable:   /opt/td-agent/embedded/bin/gem
        name:         fluent-plugin-concat
        user_install: false
